/**
 * @file peripherals.c
 * @brief  Zeus300S Peripheral setup
 *
 * Peripheral configuration for Zeus300S board.
 *
 * @note: Initial file was generated by MCUXpresso!
 *
 * @author Bram Vlerick <bram.vlerick@openpixelsystems.org>
 * @version v0.1
 * @date 2020-07-14
 * @date 2021-07-12 - davth -  Flexcomm init all
 */
#include "peripherals.h"
#include "fsl_crc.h"
#include "fsl_usart.h"
#include "board.h"

// FLEXCOMM - default settings
const usart_config_t FLEXCOMM_DEFAULT_USART_CONFIG = {
    .baudRate_Bps         = BOARD_DEBUG_USART_BAUDRATE,
    .syncMode             = kUSART_SyncModeDisabled,
    .parityMode           = kUSART_ParityDisabled,
    .stopBitCount         = kUSART_OneStopBit,
    .bitCountPerChar      = kUSART_8BitsPerChar,
    .loopback             = false,
    .txWatermark          = kUSART_TxFifo0,
    .rxWatermark          = kUSART_RxFifo1,
    .enableRx             = true,
    .enableTx             = true,
    .clockPolarity        = kUSART_RxSampleOnFallingEdge,
    .enableContinuousSCLK = false
};

// FLEXCOMM0 - Main CPU UART connection settings
const usart_config_t FLEXCOMM0_config = {
    .baudRate_Bps         = BOARD_MAINCPU_USART_BAUDRATE,
    .syncMode             = kUSART_SyncModeDisabled,
    .parityMode           = kUSART_ParityDisabled,
    .stopBitCount         = kUSART_OneStopBit,
    .bitCountPerChar      = kUSART_8BitsPerChar,
    .loopback             = false,
    .txWatermark          = kUSART_TxFifo0,
    .rxWatermark          = kUSART_RxFifo1,
    .enableRx             = true,
    .enableTx             = true,
    .clockPolarity        = kUSART_RxSampleOnFallingEdge,
    .enableContinuousSCLK = false
};

// FLEXCOMM0 - Main CPU UART connection settings
static void FLEXCOMM0_init(void) {
    /* Reset FLEXCOMM device */
    RESET_PeripheralReset(kFC0_RST_SHIFT_RSTn);
    USART_Init(FLEXCOMM0_PERIPHERAL, &FLEXCOMM0_config,
               FLEXCOMM0_CLOCK_SOURCE);
    USART_EnableInterrupts(FLEXCOMM0_PERIPHERAL,
                           kUSART_RxLevelInterruptEnable | kUSART_RxErrorInterruptEnable);
}

// FLEXCOMM1 - Gowin FPGA UART connection settings
const usart_config_t FLEXCOMM1_config = {
    .baudRate_Bps         = 57600,
    .syncMode             = kUSART_SyncModeDisabled,
    .parityMode           = kUSART_ParityDisabled,
    .stopBitCount         = kUSART_OneStopBit,
    .bitCountPerChar      = kUSART_8BitsPerChar,
    .loopback             = false,
    .txWatermark          = kUSART_TxFifo0,
    .rxWatermark          = kUSART_RxFifo1,
    .enableRx             = true,
    .enableTx             = true,
    .clockPolarity        = kUSART_RxSampleOnFallingEdge,
    .enableContinuousSCLK = false
};

static void FLEXCOMM1_init(void) {
    /* Reset FLEXCOMM device */
    RESET_PeripheralReset(kFC1_RST_SHIFT_RSTn);
    USART_Init(FLEXCOMM1_PERIPHERAL, &FLEXCOMM1_config,
               FLEXCOMM1_CLOCK_SOURCE);
    USART_EnableInterrupts(FLEXCOMM1_PERIPHERAL,
                           kUSART_RxLevelInterruptEnable | kUSART_RxErrorInterruptEnable);
}

/* Display port 1.4 Repeater device at 400kHz */
static void FLEXCOMM2_init(void) {
    i2c_master_config_t FLEXCOMM_config;

    RESET_PeripheralReset(kFC2_RST_SHIFT_RSTn);
    I2C_MasterGetDefaultConfig(&FLEXCOMM_config);
    /* Initialization function */
    I2C_MasterInit(FLEXCOMM2_PERIPHERAL, &FLEXCOMM_config,
                   FLEXCOMM2_CLOCK_SOURCE);
}

const usart_config_t FLEXCOMM3_config = FLEXCOMM_DEFAULT_USART_CONFIG;
// DEBUG UART
static void FLEXCOMM3_init(void) {
    /* Reset FLEXCOMM device */
    RESET_PeripheralReset(kFC3_RST_SHIFT_RSTn);
    USART_Init(FLEXCOMM3_PERIPHERAL, &FLEXCOMM3_config, FLEXCOMM3_CLOCK_SOURCE);
}

/* I2C Bus HUB 2 */
static void FLEXCOMM4_init(void) {
    i2c_master_config_t FLEXCOMM_config;

    RESET_PeripheralReset(kFC4_RST_SHIFT_RSTn);
    I2C_MasterGetDefaultConfig(&FLEXCOMM_config);
    /* Initialization function */
    I2C_MasterInit(FLEXCOMM4_PERIPHERAL, &FLEXCOMM_config, FLEXCOMM4_CLOCK_SOURCE);
}

/* I2C Bus HUB 1 */
static void FLEXCOMM5_init(void) {
    i2c_master_config_t FLEXCOMM_config;

    RESET_PeripheralReset(kFC5_RST_SHIFT_RSTn);
    I2C_MasterGetDefaultConfig(&FLEXCOMM_config);
    /* Initialization function */
    I2C_MasterInit(FLEXCOMM5_PERIPHERAL, &FLEXCOMM_config, FLEXCOMM5_CLOCK_SOURCE);
}

const usart_config_t FLEXCOMM6_config = FLEXCOMM_DEFAULT_USART_CONFIG;

static void FLEXCOMM6_init(void) {
    /* Reset FLEXCOMM device */
    RESET_PeripheralReset(kFC6_RST_SHIFT_RSTn);
    USART_Init(FLEXCOMM6_PERIPHERAL, &FLEXCOMM6_config, FLEXCOMM6_CLOCK_SOURCE);
}

void CRCEngine_init(CRC_Type * base, uint32_t seed) {
    crc_config_t config;

    config.polynomial = kCRC_Polynomial_CRC_32;
    config.reverseIn = true;
    config.complementIn = false;
    config.reverseOut = true;
    config.complementOut = true;
    config.seed = seed;
    CRC_Init(base, &config);
}

/* APPLICATION INIT */

void BOARD_AppInitPeripherals(void) {
    /* Initialize components */
    FLEXCOMM0_init(); // !< Main uart
    FLEXCOMM1_init(); // !< Gowin uart
    // FLEXCOMM2_init();       //!< I2C
    FLEXCOMM3_init(); // !< Debug uart
    // FLEXCOMM4_init();       //!< I2C - SLAVE , moved to i2c-routines
    // FLEXCOMM5_init();       //!< I2C - SLAVE , moved to i2c-routines
    FLEXCOMM6_init();
}

void BOARD_AppDeinitPeripherals(void) {
    USART_Deinit(FLEXCOMM0_PERIPHERAL);
    USART_Deinit(FLEXCOMM1_PERIPHERAL);
    USART_Deinit(FLEXCOMM3_PERIPHERAL);
}

/* BOOTLOADER INIT */

void BOARD_BootInitPeripherals(void) {
    /* Initialize components */
    FLEXCOMM0_init(); // !< Main uart
    FLEXCOMM3_init(); // !< Debug uart
    FLEXCOMM4_init(); // !< I2C MASTER, USB HUB
    FLEXCOMM5_init(); // !< I2C MASTER, USB HUB

    CRCEngine_init(CRC_ENGINE, 0xFFFFFFFFU);
}

void BOARD_BootDeinitPeripherals(void) {
    USART_Deinit(FLEXCOMM0_PERIPHERAL);
    CRC_Deinit(CRC_ENGINE);
}
